### ISSUE TITLE
Staff registration issue

### ISSUE THREAD

**Issue by eamkrc** [philbertphotos/osticket-multildap-auth#60]
Hi,
Trying to get Staff registration to work. Running LEMP on CentOS stack and while trying to get Automatic Staff registration to work, we're getting this error in nginx. The Staff user hasn't been pre-created. On the scp page the Authentication wheel gif just keeps spinning after pressing "Log in"

```
2022/10/19 15:28:22 [error] 27714#27714: *2142 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function checkGroup() on null in /var/www/html/osTicket/include/plugins/multi-ldap/auth.php:642
Stack trace:
#0 /var/www/html/osTicket/include/plugins/multi-ldap/auth.php(615): LDAPMultiAuthentication->authOrCreate()
#1 /var/www/html/osTicket/include/plugins/multi-ldap/auth.php(841): LDAPMultiAuthentication->authenticate()
#2 /var/www/html/osTicket/include/class.auth.php(249): StaffLDAPMultiAuthentication->authenticate()
#3 /var/www/html/osTicket/scp/login.php(71): AuthenticationBackend::process()
#4 {main}
  thrown in /var/www/html/osTicket/include/plugins/multi-ldap/auth.php on line 642" while reading response header from upstream, client: ***, server: ***, request: "POST /scp/login.php HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "***", referrer: "https://***/scp/login.php"
```

User Registration worked and searching for users also is working
System Logs show ldap-login as staff success, LDAP Sync, connect-check and ldap-search as successful as well.

> 
> Server Information
> --
> osTicket Version | v1.16.3-46-g03f8813 (03f8813)     —  Up to date
> Web Server Software | nginx/1.20.1
> MySQL Version | 5.5.68
> PHP Version | 8.0.24
> 

Appreciate all the help,
Rainer

**Comment by philbertphotos** [comment]
Right now working on 1.17 compatibility .... but let me see what I can find. It should work.

**Comment by philbertphotos** [comment]
@eamkrc should be fixed now test it and let me know.

**Comment by philbertphotos** [comment]
TO be honst I know why its doing it but did not test it ...my bad let me test and fix and update the git

**Comment by philbertphotos** [comment]
@eamkrc  the issue was the LDAP library I created was not finished so it should be working now.

**Comment by eamkrc** [comment]
Still getting a similar error sadly, tried to reinstall the plugin as well with the same result:

`2022/10/21 15:31:53 [error] 5858#5858: *176 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: ldap_search(): supplied argument is not a valid ldap link resource in /var/www/html/osTicket/include/plugins/multi-ldap/class.AuthLdap.php:361
Stack trace:
#0 /var/www/html/osTicket/include/plugins/multi-ldap/class.AuthLdap.php(361): ldap_search()
#1 /var/www/html/osTicket/include/plugins/multi-ldap/auth.php(649): AuthLdap->checkGroup()
#2 /var/www/html/osTicket/include/plugins/multi-ldap/auth.php(615): LDAPMultiAuthentication->authOrCreate()
#3 /var/www/html/osTicket/include/plugins/multi-ldap/auth.php(850): LDAPMultiAuthentication->authenticate()
#4 /var/www/html/osTicket/include/class.auth.php(249): StaffLDAPMultiAuthentication->authenticate()
#5 /var/www/html/osTicket/scp/login.php(71): AuthenticationBackend::process()
#6 {main}
  thrown in /var/www/html/osTicket/include/plugins/multi-ldap/class.AuthLdap.php on line 361" while reading response header from upstream, client: ***, server: ***, request: "POST /scp/login.php HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "***", referrer: "***/scp/login.php"`

Best Regards,
Rainer

**Comment by philbertphotos** [comment]
That fixed it on my end I have no idea why you getting this error but let me double check a few things.

**Comment by philbertphotos** [comment]
@eamkrc So its FIXED
(1) Updated to 1.16.3 (was using 1.15.3)
(2) Updated general code for PHP 8.0 is also compatible with osticket 1.17
(3) Extensive testing because some core changes created a problem with staff creation 

So by default it adds newly created staff as a Agent with permission to the first Department 
TO:DO
List default department for new staff creation and what the default roles will be.

For now when a member is created you have to eventually go in and set the roles and departments they need to be in.
